### PR TITLE
Bugfix data casting

### PR DESCRIPTION
**Pull request by sirwolfgang**
In Rails 5.2, and maybe other versions, cast gets called during the assignment and sometimes is used to attempt to expand a valid UUID. This is to skip casting if the value already looks like a UUID.

I am not sure what tests to add, I only noticed this issue when running my app instance in development and not during any of my normal test coverage. Which is odd because I would expect requests or controller specs to have triggered this issue.

### CODE REVIEW

**Comment by markoudev** [comment]
Thank you for your pull request! I recognise the issue you bring up (noticed it during development), and I think the place where you placed the additional comparison makes sense if you read the comments there as to why we're doing that comparison. I'm glad you mention as to why `cast` is sometimes mentioned.

It would be nice if we have a test for this indeed. Would you mind adding one? I think you should be able to use `String#encode` to change the encoding and make sure your comparison is hit.

Current version:

```
mysql-binuuid-rails $ bin/console
irb(main):001:0> MySQLBinUUID::Type.new.cast(SecureRandom.uuid.encode(Encoding::ASCII_8BIT))
=> "33623866-3530-3633-2d64-6262332d343631652d393861662d323565643537343161353761"
irb(main):002:0>
```

With your fix (works as expected!)

```
mysql-binuuid-rails $ bin/console
irb(main):001:0> MySQLBinUUID::Type.new.cast(SecureRandom.uuid.encode(Encoding::ASCII_8BIT))
=> "6095e58b-7dd2-4fda-b471-a1bda0ebf411"
irb(main):002:0>

**Comment by sirwolfgang** [comment]
@markoudev PR Updated

**Comment by markoudev** [comment]
Wonderful, thanks! I'll merge it and an going to create a new version.

**Comment by markoudev** [comment]
Release in version 1.2.0!

**Pull request merged**
